export default {
  id: "qoder-cn",
  priority: 30,
  alias: "qdcn",
  uiAlias: "qdcn",
  display: {
    name: "Qoder CN",
    icon: "water_drop",
    color: "#EC4899",
    website: "https://qoder.com.cn",
    notice: {
      signupUrl: "https://qoder.com.cn",
    },
  },
  category: "oauth",
  authModes: ["oauth", "apikey"],
  hasOAuth: true,
  authHint: "Personal Access Token (pt-...) from https://qoder.com.cn/account/integrations",
  transport: {
    baseUrl: "https://gateway.qoder.com.cn/algo/api/v2/service/pro/sse/agent_chat_generation",
    headers: {},
    timeoutMs: 120000,
    stallTimeoutMs: 120000,
    usage: {
      url: "https://openapi.qoder.com.cn/api/v2/quota/usage",
    },
  },
  models: [
    { id: "ultimate", name: "Ultimate" },
    { id: "auto", name: "Auto" },
    { id: "performance", name: "Performance" },
    { id: "efficient", name: "Efficient" },
    { id: "lite", name: "Lite" },
    { id: "qmodel_38max", name: "Qwen3.8-Max" },
    { id: "qmodel_latest", name: "Qwen3.7-Max" },
    { id: "qmodel", name: "Qwen3.7-Plus" },
    { id: "qfmodel", name: "Qwen3.8-Flash" },
    { id: "kmodel_latest", name: "Kimi-K3" },
    { id: "kmodel", name: "Kimi-K2.8-Preview" },
    { id: "gmodel", name: "GLM-5.3" },
    { id: "gfmodel", name: "GLM-5.3-Flash" },
    { id: "dmodel", name: "DeepSeek-V4-Pro" },
    { id: "dfmodel", name: "DeepSeek-V4.1-Flash" },
    { id: "mmodel", name: "MiniMax-M2.7" },
  ],
  // v0.8.9 — 上游代号 → 友好名（以上游目录实际显示名为准）。代号是上游契约（执行器按该 key
  // 查 model_config），不能改 id；这里只做「展示 + 调用」两层归一化，且仅在本提供商前缀
  // （qdcn/）下生效，裸名行为不变。q37fmodel / gm51model 是账号目录里额外下发的代号（注册表
  // 静态表未列），一并登记以便展示与直呼。
  modelAliases: {
    qmodel_38max: "qwen3.8-max",
    qmodel_latest: "qwen3.7-max",
    qmodel: "qwen3.7-plus",
    qfmodel: "qwen3.8-flash",
    q37fmodel: "qwen3.7-flash",
    kmodel_latest: "kimi-k3",
    kmodel: "kimi-k2.8-preview",
    gmodel: "glm-5.3",
    gfmodel: "glm-5.3-flash",
    gm51model: "glm-5.2",
    dmodel: "deepseek-v4-pro",
    dfmodel: "deepseek-v4.1-flash",
    mmodel: "minimax-m2.7",
  },
  oauth: {
    openApiBaseUrl: "https://openapi.qoder.com.cn",
    centerBaseUrl: "https://gateway.qoder.com.cn",
    chatBaseUrl: "https://gateway.qoder.com.cn",
    deviceTokenUrl: "https://openapi.qoder.com.cn/api/v1/deviceToken/poll",
    refreshUrl: "https://gateway.qoder.com.cn/algo/api/v3/user/refresh_token",
    userInfoUrl: "https://openapi.qoder.com.cn/api/v1/userinfo",
    quotaUsageUrl: "https://openapi.qoder.com.cn/api/v2/quota/usage",
    loginUrl: "https://qoder.com.cn/device/selectAccounts",
  },
  features: {
    usage: true,
    // PAT (apikey) connections also carry quota usage (via job-token exchange).
    usageApikey: true,
  },
};
